# Generated by Django 4.0.6 on 2023-12-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_wallet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_operation',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_operation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
